remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: Christopher Sharp
description: B.S. in Computer Science, Information Security Concentration | Southern New Hampshire University, Class of 2025  


