remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: Christopher Sharp
description: This ePortfolio was created for my CS-499 Capstone Project at Southern New Hampshire University (SNHU). It is being used to showcase my growth throughout the Computer Science program.

