remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: Christopher Sharp
description: Portfolio website for CS 499

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
